language: android

android:
  components:
    # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-29.0.2

    # The SDK version used to compile your project
    - android-29

jdk:
  - oraclejdk8

sudo: required

script: ./gradlew assemblePlainDebug assemblePlainRelease
